import { httpServerHandler } from 'cloudflare:node';
import express from 'express';

const app = express();
app.use(express.json());

const INSTALL_SH = `
IyEvYmluL3NoCgojIEZyb20gaHR0cHM6Ly9naXRodWIuY29tL0hvbWVicmV3L2luc3RhbGwvYmxvYi9tYXN0ZXIvaW5zdGFsbC5zaAphYm9ydCgpIHsKICBwcmludGYgIiVzXG4iICIkQCIKICBleGl0IDEKfQoKIyBzdHJpbmcgZm9ybWF0dGVycwppZiBbIC10IDEgXTsgdGhlbgogIHR0eV9lc2NhcGUoKSB7IHByaW50ZiAiXDAzM1slc20iICIkMSI7IH0KZWxzZQogIHR0eV9lc2NhcGUoKSB7IDo7IH0KZmkKdHR5X21rYm9sZCgpIHsgdHR5X2VzY2FwZSAiMTskMSI7IH0KdHR5X2JsdWU9IiQodHR5X21rYm9sZCAzNCkiCnR0eV9ib2xkPSIkKHR0eV9ta2JvbGQgMzkpIgp0dHlfcmVzZXQ9IiQodHR5X2VzY2FwZSAwKSIKCm9oYWkoKSB7CiAgcHJpbnRmICIke3R0eV9ibHVlfT09PiR7dHR5X2JvbGR9ICVzJHt0dHlfcmVzZXR9XG4iICIkMSIKfQoKIyBFbmQgZnJvbSBodHRwczovL2dpdGh1Yi5jb20vSG9tZWJyZXcvaW5zdGFsbC9ibG9iL21hc3Rlci9pbnN0YWxsLnNoCgpkb3dubG9hZCgpIHsKICBpZiBjb21tYW5kIC12IGN1cmwgPiAvZGV2L251bGwgMj4mMTsgdGhlbgogICAgY3VybCAtZnNTTCAiJDEiCiAgZWxzZQogICAgd2dldCAtcU8tICIkMSIKICBmaQp9Cgppc19nbGliY19jb21wYXRpYmxlKCkgewogIGdldGNvbmYgR05VX0xJQkNfVkVSU0lPTiA+L2Rldi9udWxsIDI+JjEgfHwgbGRkIC0tdmVyc2lvbiA+L2Rldi9udWxsIDI+JjEgfHwgcmV0dXJuIDEKfQoKZGV0ZWN0X3BsYXRmb3JtKCkgewogIGxvY2FsIHBsYXRmb3JtCiAgcGxhdGZvcm09IiQodW5hbWUgLXMgfCB0ciAnWzp1cHBlcjpdJyAnWzpsb3dlcjpdJykiCgogIGNhc2UgIiR7cGxhdGZvcm19IiBpbgogICAgbGludXgpCiAgICAgIGlmIGlzX2dsaWJjX2NvbXBhdGlibGU7IHRoZW4KICAgICAgICBwbGF0Zm9ybT0ibGludXgiCiAgICAgIGVsc2UKICAgICAgICBwbGF0Zm9ybT0ibGludXhzdGF0aWMiCiAgICAgIGZpCiAgICAgIDs7CiAgICBkYXJ3aW4pIHBsYXRmb3JtPSJtYWNvcyIgOzsKICAgIHdpbmRvd3MpIHBsYXRmb3JtPSJ3aW4iIDs7CiAgICBtaW5ndyopIHBsYXRmb3JtPSJ3aW4iIDs7CiAgZXNhYwoKICBwcmludGYgJyVzJyAiJHtwbGF0Zm9ybX0iCn0KCmRldGVjdF9hcmNoKCkgewogIGxvY2FsIGFyY2gKICBhcmNoPSIkKHVuYW1lIC1tIHwgdHIgJ1s6dXBwZXI6XScgJ1s6bG93ZXI6XScpIgoKICBjYXNlICIke2FyY2h9IiBpbgogICAgeDg2XzY0IHwgYW1kNjQpIGFyY2g9Ing2NCIgOzsKICAgIGFybXYqKSBhcmNoPSJhcm0iIDs7CiAgICBhcm02NCB8IGFhcmNoNjQpIGFyY2g9ImFybTY0IiA7OwogIGVzYWMKCiAgIyBgdW5hbWUgLW1gIGluIHNvbWUgY2FzZXMgbWlzLXJlcG9ydHMgMzItYml0IE9TIGFzIDY0LWJpdCwgc28gZG91YmxlIGNoZWNrCiAgaWYgWyAiJHthcmNofSIgPSAieDY0IiBdICYmIFsgIiQoZ2V0Y29uZiBMT05HX0JJVCkiIC1lcSAzMiBdOyB0aGVuCiAgICBhcmNoPWk2ODYKICBlbGlmIFsgIiR7YXJjaH0iID0gImFybTY0IiBdICYmIFsgIiQoZ2V0Y29uZiBMT05HX0JJVCkiIC1lcSAzMiBdOyB0aGVuCiAgICBhcmNoPWFybQogIGZpCgogIGNhc2UgIiRhcmNoIiBpbgogICAgeDY0KikgOzsKICAgIGFybTY0KikgOzsKICAgICopIHJldHVybiAxCiAgZXNhYwogIHByaW50ZiAnJXMnICIke2FyY2h9Igp9Cgpkb3dubG9hZF9hbmRfaW5zdGFsbCgpIHsKICBsb2NhbCBwbGF0Zm9ybSBhcmNoIHZlcnNpb25fanNvbiB2ZXJzaW9uIGFyY2hpdmVfdXJsIHRtcF9kaXIKICBwbGF0Zm9ybT0iJChkZXRlY3RfcGxhdGZvcm0pIgogIGFyY2g9IiQoZGV0ZWN0X2FyY2gpIiB8fCBhYm9ydCAiU29ycnkhIHBucG0gY3VycmVudGx5IG9ubHkgcHJvdmlkZXMgcHJlLWJ1aWx0IGJpbmFyaWVzIGZvciB4ODZfNjQvYXJtNjQgYXJjaGl0ZWN0dXJlcy4iCiAgaWYgWyAteiAiJHtQTlBNX1ZFUlNJT059IiBdOyB0aGVuCiAgICB2ZXJzaW9uX2pzb249IiQoZG93bmxvYWQgImh0dHBzOi8vcmVnaXN0cnkubnBtanMub3JnL0BwbnBtL2V4ZSIpIiB8fCBhYm9ydCAiRG93bmxvYWQgRXJyb3IhIgogICAgdmVyc2lvbj0iJChlY2hvICIkdmVyc2lvbl9qc29uIiB8IGdyZXAgLW8gJyJsYXRlc3QiOltbOnNwYWNlOl1dKiJbMC05Ll0qIicgfCBncmVwIC1vICdbMC05Ll0qJykiCiAgZWxzZQogICAgdmVyc2lvbj0iJHtQTlBNX1ZFUlNJT059IgogIGZpCgogIGFyY2hpdmVfdXJsPSJodHRwczovL3BucG0uYmVpbmd0aGluay5jb20vcG5wbS9wbnBtL3JlbGVhc2VzL2Rvd25sb2FkL3Yke3ZlcnNpb259L3BucG0tJHtwbGF0Zm9ybX0tJHthcmNofSIKICBpZiBbICIke3BsYXRmb3JtfSIgPSAid2luIiBdOyB0aGVuCiAgICBhcmNoaXZlX3VybD0iJHthcmNoaXZlX3VybH0uZXhlIgogIGZpCgogICMgaW5zdGFsbCB0byBQTlBNX0hPTUUsIGRlZmF1bHRpbmcgdG8gfi8ucG5wbQogIHRtcF9kaXI9IiQobWt0ZW1wIC1kKSIgfHwgYWJvcnQgIlRtcGRpciBFcnJvciEiCiAgIyBVc2UgZG91YmxlIHF1b3RlcyB3aXRoIHNpbmdsZS1xdW90ZWQgdmFyaWFibGUgdG8gaW50ZXJwb2xhdGUgYXQgdHJhcCBzZXR1cCB0aW1lLgogICMgVGhpcyBlbnN1cmVzIHRoZSBkaXJlY3RvcnkgcGF0aCBpcyBjYXB0dXJlZCBldmVuIGlmIHRtcF9kaXIgZ29lcyBvdXQgb2Ygc2NvcGUuCiAgIyBzaGVsbGNoZWNrIGRpc2FibGU9U0MyMDY0CiAgdHJhcCAicm0gLXJmICckdG1wX2RpciciIEVYSVQgSU5UIFRFUk0gSFVQCgogIG9oYWkgIkRvd25sb2FkaW5nIHBucG0gYmluYXJpZXMgJHt2ZXJzaW9ufSIKICAjIGRvd25sb2FkIHRoZSBiaW5hcnkgdG8gdGhlIHNwZWNpZmllZCBkaXJlY3RvcnkKICBkb3dubG9hZCAiJGFyY2hpdmVfdXJsIiA+ICIkdG1wX2Rpci9wbnBtIiAgfHwgcmV0dXJuIDEKICBjaG1vZCAreCAiJHRtcF9kaXIvcG5wbSIKICBTSEVMTD0iJFNIRUxMIiAiJHRtcF9kaXIvcG5wbSIgc2V0dXAgLS1mb3JjZSB8fCByZXR1cm4gMQp9Cgpkb3dubG9hZF9hbmRfaW5zdGFsbCB8fCBhYm9ydCAiSW5zdGFsbCBFcnJvciEiCg==
`;
const INSTALL_PS1 = `
IyEvdXNyL2Jpbi9lbnYgcHdzaAoKIyBTdG9wIGV4ZWN1dGluZyBzY3JpcHQgb24gYW55IGVycm9yCiRFcnJvckFjdGlvblByZWZlcmVuY2UgPSAnU3RvcCcKIyBEbyBub3Qgc2hvdyBkb3dubG9hZCBwcm9ncmVzcwokUHJvZ3Jlc3NQcmVmZXJlbmNlID0gJ1NpbGVudGx5Q29udGludWUnCgojIFRha2VuIGZyb20gaHR0cHM6Ly9zdGFja292ZXJmbG93LmNvbS9hLzM0NTU5NTU0LzY1Mzc0MjAKZnVuY3Rpb24gTmV3LVRlbXBvcmFyeURpcmVjdG9yeSB7CiAgJHBhcmVudCA9IFtTeXN0ZW0uSU8uUGF0aF06OkdldFRlbXBQYXRoKCkKICBbc3RyaW5nXSAkbmFtZSA9IFtTeXN0ZW0uR3VpZF06Ok5ld0d1aWQoKQogIE5ldy1JdGVtIC1JdGVtVHlwZSBEaXJlY3RvcnkgLVBhdGggKEpvaW4tUGF0aCAkcGFyZW50ICRuYW1lKQp9CgokcGxhdGZvcm0gPSAkbnVsbAokYXJjaGl0ZWN0dXJlID0gJG51bGwKJHBucG1OYW1lID0gJG51bGwKCiMgUG93ZXJTaGVsbCB2ZXJzaW9ucyBiZWZvcmUgNi4qIHdlcmUgb25seSBmb3IgV2luZG93cyBPUwppZiAoJFBTVmVyc2lvblRhYmxlLlBTVmVyc2lvbi5NYWpvciAtZXEgNSkgewogICRwbGF0Zm9ybSA9ICd3aW4nCn0KCmlmICgkUFNWZXJzaW9uVGFibGUuUFNWZXJzaW9uLk1ham9yIC1nZSA2KSB7CiAgaWYgKCRQU1ZlcnNpb25UYWJsZS5QbGF0Zm9ybSAtZXEgJ1VuaXgnKSB7CiAgICBzd2l0Y2ggLVdpbGRjYXJkICgkUFNWZXJzaW9uVGFibGUuT1MpIHsKICAgICAgJ0RhcndpbionIHsKICAgICAgICAkcGxhdGZvcm0gPSAnbWFjb3MnCiAgICAgIH0KICAgICAgJ0xpbnV4KicgewogICAgICAgICRwbGF0Zm9ybSA9ICdsaW51eCcKICAgICAgfQogICAgICAnVWJ1bnR1KicgewogICAgICAgICRwbGF0Zm9ybSA9ICdsaW51eCcKICAgICAgfQogICAgfQoKICAgICMgUG93ZXJTaGVsbCBkb2VzIG5vdCBzZWVtIHRvIGhhdmUgbm9ybWFsIGNtZGxldHMgZm9yIHJldHJpZXZpbmcgc3lzdGVtIGluZm9ybWF0aW9uLCBzbyB3ZSB1c2UgVU5BTUUoMSkgZm9yIHRoaXMuCiAgICAkYXJjaCA9IHVuYW1lIC1tCiAgICBzd2l0Y2ggLVdpbGRjYXJkICgkYXJjaCkgewogICAgICAneDg2XzY0JyB7ICRhcmNoaXRlY3R1cmUgPSAneDY0JzsgQnJlYWsgfQogICAgICAnYW1kNjQnIHsgJGFyY2hpdGVjdHVyZSA9ICd4NjQnOyBCcmVhayB9CiAgICAgICdhcm12KicgeyAkYXJjaGl0ZWN0dXJlID0gJ2FybSc7IEJyZWFrIH0KICAgICAgJ2FybTY0JyB7ICRhcmNoaXRlY3R1cmUgPSAnYXJtNjQnOyBCcmVhayB9CiAgICAgICdhYXJjaDY0JyB7ICRhcmNoaXRlY3R1cmUgPSAnYXJtNjQnOyBCcmVhayB9CiAgICB9CgogICAgIyAndW5hbWUgLW0nIGluIHNvbWUgY2FzZXMgbWlzLXJlcG9ydHMgMzItYml0IE9TIGFzIDY0LWJpdCwgc28gZG91YmxlIGNoZWNrCiAgICBpZiAoW1N5c3RlbS5FbnZpcm9ubWVudF06OklzNjRCaXRPcGVyYXRpbmdTeXN0ZW0gLWVxICRmYWxzZSkgewogICAgICBpZiAoJGFyY2hpdGVjdHVyZSAtZXEgJ3g2NCcpIHsKICAgICAgICAkYXJjaGl0ZWN0dXJlID0gJ2k2ODYnCiAgICAgIH0KCiAgICAgIGlmICgkYXJjaGl0ZWN0dXJlIC1lcSAnYXJtNjQnKSB7CiAgICAgICAgJGFyY2hpdGVjdHVyZSA9ICdhcm0nCiAgICAgIH0KICAgIH0KCiAgICAkcG5wbU5hbWUgPSAicG5wbSIKICB9CgogIGlmICgkUFNWZXJzaW9uVGFibGUuUGxhdGZvcm0gLWVxICdXaW4zMk5UJykgewogICAgJHBsYXRmb3JtID0gJ3dpbicKICB9Cn0KCmlmICgkcGxhdGZvcm0gLWVxICd3aW4nKSB7CiAgaWYgKFtTeXN0ZW0uRW52aXJvbm1lbnRdOjpJczY0Qml0T3BlcmF0aW5nU3lzdGVtIC1lcSAkdHJ1ZSkgewogICAgJGFyY2hpdGVjdHVyZSA9ICd4NjQnCiAgfQoKICBpZiAoW1N5c3RlbS5FbnZpcm9ubWVudF06OklzNjRCaXRPcGVyYXRpbmdTeXN0ZW0gLWVxICRmYWxzZSkgewogICAgJGFyY2hpdGVjdHVyZSA9ICdpNjg2JwogIH0KCiAgJHBucG1OYW1lID0gInBucG0uZXhlIgp9CgppZiAoJG51bGwgLWVxICRwbGF0Zm9ybSkgewogIFdyaXRlLUVycm9yICJQbGF0Zm9ybSBjb3VsZCBub3QgYmUgZGV0ZXJtaW5lZCEgT25seSBXaW5kb3dzLCBMaW51eCBhbmQgTWFjT1MgYXJlIHN1cHBvcnRlZC4iCn0KCnN3aXRjaCAoJGFyY2hpdGVjdHVyZSkgewogICd4NjQnIHsgOyBCcmVhayB9CiAgJ2FybTY0JyB7IDsgQnJlYWsgfQogIERlZmF1bHQgewogICAgV3JpdGUtRXJyb3IgIlNvcnJ5ISBwbnBtIGN1cnJlbnRseSBvbmx5IHByb3ZpZGVzIHByZS1idWlsdCBiaW5hcmllcyBmb3IgeDg2XzY0L2FybTY0IGFyY2hpdGVjdHVyZXMuIgogIH0KfQoKW05ldC5TZXJ2aWNlUG9pbnRNYW5hZ2VyXTo6U2VjdXJpdHlQcm90b2NvbCA9IFtOZXQuU2VjdXJpdHlQcm90b2NvbFR5cGVdOjpUbHMxMgoKJHBrZ0luZm8gPSBJbnZva2UtV2ViUmVxdWVzdCAiaHR0cHM6Ly9yZWdpc3RyeS5ucG1qcy5vcmcvQHBucG0vZXhlIiAtVXNlQmFzaWNQYXJzaW5nCiR2ZXJzaW9uSnNvbiA9ICRwa2dJbmZvLkNvbnRlbnQgfCBDb252ZXJ0RnJvbS1Kc29uCiR2ZXJzaW9ucyA9IEdldC1NZW1iZXIgLUlucHV0T2JqZWN0ICR2ZXJzaW9uSnNvbi52ZXJzaW9ucyAtVHlwZSBOb3RlUHJvcGVydHkgfCBTZWxlY3QtT2JqZWN0IC1FeHBhbmRQcm9wZXJ0eSBOYW1lCiRkaXN0VGFncyA9IEdldC1NZW1iZXIgLUlucHV0T2JqZWN0ICR2ZXJzaW9uSnNvbi4nZGlzdC10YWdzJyAtVHlwZSBOb3RlUHJvcGVydHkgfCBTZWxlY3QtT2JqZWN0IC1FeHBhbmRQcm9wZXJ0eSBOYW1lCgokdmVyc2lvbiA9ICRudWxsCiRwcmVmZXJyZWRWZXJzaW9uID0gImxhdGVzdCIKCmlmICgkbnVsbCAtbmUgJGVudjpQTlBNX1ZFUlNJT04gLWFuZCAkZW52OlBOUE1fVkVSU0lPTiAtbmUgIiIpIHsKICAkcHJlZmVycmVkVmVyc2lvbiA9ICRlbnY6UE5QTV9WRVJTSU9OCn0KCmlmICgkbnVsbCAtZXEgJHZlcnNpb24gLWFuZCAkcHJlZmVycmVkVmVyc2lvbiAtaW4gJGRpc3RUYWdzKSB7CiAgJHZlcnNpb24gPSAkdmVyc2lvbkpzb24uJ2Rpc3QtdGFncycgfCBTZWxlY3QtT2JqZWN0IC1FeHBhbmRQcm9wZXJ0eSAkcHJlZmVycmVkVmVyc2lvbgp9CgppZiAoJG51bGwgLWVxICR2ZXJzaW9uIC1hbmQgJHByZWZlcnJlZFZlcnNpb24gLWluICR2ZXJzaW9ucykgewogICR2ZXJzaW9uID0gJHByZWZlcnJlZFZlcnNpb24KfQoKaWYgKCRudWxsIC1lcSAkdmVyc2lvbikgewogIFdyaXRlLUhvc3QgIkN1cnJlbnQgdGFnczoiIC1Gb3JlZ3JvdW5kQ29sb3IgWWVsbG93IC1Ob05ld2xpbmUKICAkdmVyc2lvbkpzb24uJ2Rpc3QtdGFncycgfCBGb3JtYXQtTGlzdAoKICBXcml0ZS1Ib3N0ICJWZXJzaW9uczoiIC1Gb3JlZ3JvdW5kQ29sb3IgWWVsbG93IC1Ob05ld2xpbmUKICAkdmVyc2lvbkpzb24udmVyc2lvbnMgfCBHZXQtTWVtYmVyIC1UeXBlIE5vdGVQcm9wZXJ0eSB8IEZvcm1hdC1XaWRlIC1Qcm9wZXJ0eSBOYW1lIC1BdXRvU2l6ZQoKICBXcml0ZS1FcnJvciAiU29ycnkhIHBucG0gJyRwcmVmZXJyZWRWZXJzaW9uJyB2ZXJzaW9uIGNvdWxkIG5vdCBiZSBmb3VuZC4gVXNlIG9uZSBvZiB0aGUgdGFncyBvciBwdWJsaXNoZWQgdmVyc2lvbnMgZnJvbSB0aGUgcHJvdmlkZWQgbGlzdCIKfQoKV3JpdGUtSG9zdCAiRG93bmxvYWRpbmcgcG5wbSBmcm9tIEdpdEh1Yi4uLmBuIiAtRm9yZWdyb3VuZENvbG9yIEdyZWVuCgokdGVtcEZpbGVGb2xkZXIgPSBOZXctVGVtcG9yYXJ5RGlyZWN0b3J5CiR0ZW1wRmlsZSA9IChKb2luLVBhdGggJHRlbXBGaWxlRm9sZGVyLkZ1bGxOYW1lICRwbnBtTmFtZSkKJGFyY2hpdmVVcmw9Imh0dHBzOi8vcG5wbS5iZWluZ3RoaW5rLmNvbS9wbnBtL3BucG0vcmVsZWFzZXMvZG93bmxvYWQvdiR2ZXJzaW9uL3BucG0tJHBsYXRmb3JtLSRhcmNoaXRlY3R1cmUiCmlmICgkcGxhdGZvcm0gLWVxICd3aW4nKSB7CiAgJGFyY2hpdmVVcmw9IiRhcmNoaXZlVXJsLmV4ZSIKfQpJbnZva2UtV2ViUmVxdWVzdCAkYXJjaGl2ZVVybCAtT3V0RmlsZSAkdGVtcEZpbGUgLVVzZUJhc2ljUGFyc2luZwoKV3JpdGUtSG9zdCAiUnVubmluZyBzZXR1cC4uLmBuIiAtRm9yZWdyb3VuZENvbG9yIEdyZWVuCgppZiAoJHBsYXRmb3JtIC1uZSAnd2luJykgewogIGNobW9kICt4ICR0ZW1wRmlsZQp9CgpTdGFydC1Qcm9jZXNzIC1GaWxlUGF0aCAkdGVtcEZpbGUgLUFyZ3VtZW50TGlzdCAic2V0dXAiIC1Ob05ld1dpbmRvdyAtV2FpdCAtRXJyb3JBY3Rpb24gQ29udGludWUKClJlbW92ZS1JdGVtICR0ZW1wRmlsZQpSZW1vdmUtSXRlbSAkdGVtcEZpbGVGb2xkZXIgLVJlY3Vyc2UK
`;
async function proxyPnpm(res: any, version: string, arch: string) {
	const targetUrl = `https://github.com/pnpm/pnpm/releases/download/${version}/${arch}`;

	try {
		// 使用 fetch 代替 https.get，fetch 自动处理 302 重定向
		const githubRes = await fetch(targetUrl, {
			redirect: 'follow',
		});

		if (!githubRes.ok) {
			return res.status(githubRes.status).send('GitHub Error');
		}

		// 设置响应头（透传类型和长度）
		res.setHeader('Content-Type', githubRes.headers.get('Content-Type') || 'application/octet-stream');
		const contentLength = githubRes.headers.get('Content-Length');
		if (contentLength) res.setHeader('Content-Length', contentLength);

		// 关键：将 fetch 的 Web Stream 转换为 Node 能够处理的流（或直接传输）
		// Cloudflare 环境下，githubRes.body 是一个 ReadableStream
		if (githubRes.body) {
			const reader = githubRes.body.getReader();

			// 循环读取流并写入 express 的 response
			while (true) {
				const { done, value } = await reader.read();
				if (done) break;
				res.write(value);
			}
		}
		res.end();
	} catch (error: any) {
		console.error('Fetch Error:', error);
		res.status(500).send('Proxy error: ' + error.message);
	}
}

const router = express.Router();

router.get('/:version/:arch', async (req, res) => {
	if (req.params.arch && req.params.version) {
		await proxyPnpm(res, req.params.version, req.params.arch);
	} else {
		res.status(404).send('File not found');
	}
});

// 解决脚本中curl head验证请求
router.head('/:version/:arch', (req, res) => {
	res.status(200).end();
});

app.get('/install.sh', (req, res) => {
	res.setHeader('Content-Type', 'text/x-shellscript');
	res.send(Buffer.from(INSTALL_SH, 'base64').toString('utf-8'));
});

app.get('/install.ps1', (req, res) => {
	res.setHeader('Content-Type', 'application/powershell');
	res.send(Buffer.from(INSTALL_PS1, 'base64').toString('utf-8'));
});

app.use('/pnpm/pnpm/releases/download', router);
app.listen(3000, () => {
	console.log('Server is running on port 3000');
});

export default httpServerHandler({ port: 3000 });
